### ISSUE TITLE
AttributeError: module 'warprnnt_pytorch' has no attribute 'cpu_rnnt

### ISSUE THREAD

**Issue by germany-zhu** [HawkAaron/warp-transducer#36]
When I run test.py in pytorch_binding/test, I got the following error:
```Traceback (most recent call last):
  File "test.py", line 165, in <module>
    small_test()
  File "test.py", line 60, in small_test
    cost, grads = wrap_and_call(acts, labels)
  File "test.py", line 44, in wrap_and_call
    costs = fn(acts, labels, lengths, label_lengths)
  File "/home/zhuminxian/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/zhuminxian/ASR/RNN-T/warp-transducer/pytorch_binding/warprnnt_pytorch/__init__.py", line 100, in forward
    return self.loss(acts, labels, act_lens, label_lens, self.blank, self.reduction)
  File "/data2/zhuminxian/ASR/RNN-T/warp-transducer/pytorch_binding/warprnnt_pytorch/__init__.py", line 23, in forward
    loss_func = warp_rnnt.gpu_rnnt if is_cuda else warp_rnnt.cpu_rnnt
AttributeError: module 'warprnnt_pytorch' has no attribute 'cpu_rnnt'
```

It seems there is neither gpu_rnnt or cpu_rnnt  in line 23 of pytorch_binding/warprnnt_pytorch/__init__.py.
Is it my problem about installation, or others?

**Comment by HawkAaron** [comment]
Please run test.py outside the pytorch_binding dir.

**Comment by germany-zhu** [comment]
Thanks for your reply.
The problem remains when I  run test.py outside the pytorch_binding dir.
Besides, the same error occurs when I run the other code that  call the RNNTLoss object.
Actually I annotated line 6 in pytorch_binding/warprnnt_pytorch/__init__.py,  
otherwise another error will occur:
```
Traceback (most recent call last):
  File "test/test.py", line 17, in <module>
    from warprnnt_pytorch import RNNTLoss
  File "/data2/zhuminxian/ASR/RNN-T/warp-transducer/pytorch_binding/warprnnt_pytorch/__init__.py", line 6, in <module>
    from .warp_rnnt import *
ModuleNotFoundError: No module named 'warprnnt_pytorch.warp_rnnt'
```
 I  cann't figure out why.

**Comment by HawkAaron** [comment]
Please follow the [installation instructions](https://github.com/HawkAaron/warp-transducer/blob/master/pytorch_binding/README.md#installation).

**Comment by germany-zhu** [comment]
Thanks...

**Comment by feipeng-wang** [comment]
@germany-zhu ，Did you solve the problem. Would you please share? Thanks

**Comment by DavidHoessle** [comment]
It didn't work for me as well then I realized the reason was that I was still in the `pytorch_bindings` folder.
Anywhere else it works like a charm.
