### ISSUE TITLE
multi-gpu

### ISSUE THREAD

**Issue by lijiangguo** [HawkAaron/warp-transducer#54]
Hi, 

I am using pytorch with dataparallel on 2 GPUs but has "ValueError("Input length mismatch")" when computing loss. Have you tested it on multi-gpu? 

`Traceback (most recent call last):
...
line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "model.py", line 86, in forward
    loss = self.loss(out, ys.int(), xlen, ylen)
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 100, in forward
    return self.loss(acts, labels, act_lens, label_lens, self.blank, self.reduction)
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 21, in forward
    certify_inputs(acts, labels, act_lens, label_lens)
  File "venv_rnnt_pytorch/lib64/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 138, in certify_inputs
    raise ValueError("Input length mismatch")
ValueError: Input length mismatch`

**Comment by mjh2040** [comment]
i think you consider using distributed data parallel. The error occured because dataparallel splits your data into the number of available gpus and except one of your batches don't have maximum length data.

**Comment by lijiangguo** [comment]
Hi @mjh2040 , I have verified that the data size before model forward call and during forward call and the lengths are equal because of padding:

```
Outside: input size torch.Size([16, 42, 1025]) output_size torch.Size([16, 16]) torch.Size([16]) torch.Size([16])
	In Model: input size torch.Size([8, 42, 1025]) output size torch.Size([8, 16]) torch.Size([8]) torch.Size([8])
	In Model: input size torch.Size([8, 42, 1025]) output size torch.Size([8, 16]) torch.Size([8]) torch.Size([8])

```
I wonder if someone has tested on multi-gpu?

**Comment by meixitu** [comment]
Hi @lijiangguo,
    I tried the multi-GPU, and found the batch size mismatch with the label_length size
    because, label_length = n, and batch size = n*num_gpus
    One GPU works well.
    Did you fix this issue?

Thanks
Jinhong

**Comment by meixitu** [comment]
Hi @lijiangguo,
    I think i meet the same issue for the multi-gpu, because input_length = n, and batch_size=n * num_gpus
    Did you fix this issue?

Thanks
