### ISSUE TITLE
undefined symbol issue when importing TensorFlow binding

### ISSUE THREAD

**Issue by naxingyu** [HawkAaron/warp-transducer#78]
In the `tensorflow_binding` folder, I did the op header copy
```
cp ../../tensorflow/tensorflow/core/framework/op.h /usr/local/lib/python3.6/site-packages/tensorflow/core/framework
cp ../../tensorflow/tensorflow/core/framework/op.h ../include/
cp ../../tensorflow/tensorflow/core/framework/op.h include/
```
and build using
```
TF_CXX11_ABI=1 CUDA_HOME=/usr/local/cuda python3 setup.py install
```
then importing the module give me error like this 
```
>>> import warprnnt_tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/warprnnt_tensorflow-0.1-py3.6-linux-x86_64.egg/warprnnt_tensorflow/__init__.py", line 6, in <module>
    _warprnnt = tf.load_op_library(lib_file)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/site-packages/warprnnt_tensorflow-0.1-py3.6-linux-x86_64.egg/warprnnt_tensorflow/kernels.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE
```
Anything I missed?

**Comment by YoPatapon** [comment]
Have you solved the problem?
